<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Inscrever-se</title>
</head>
<body>
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img class="img-logo" src="/img/x_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome']?>" name="nome"  class="form-control" placeholder="Nome">
              </div>

              <div class="form-group">
                <input type="text" name="nickname" value="@"  class="form-control" placeholder="Preencha seu @">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email']?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" name="senha" class="form-control" placeholder="Senha">
              </div>

              <div class="form-group">
                <label for="imagem"> Selecione uma foto de perfil</label>
                <input type="file" name="imagem" class="form-control" placeholder="Senha"> 
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-button btn-block">Inscrever-se</button>

              <?php 
                    if($this->view->erroCadastro) {?>
                      <small class="text-danger form-text text-center"> Ocorreu um ero, por favor digite um e-mail, nome ou NickName válido </small>
                    <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    

</body>
</html>
  