<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Veja quem você quer seguir</title>
</head>
<body class="bannert">
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div  class="navbar" >	
		<div>
			<a class="navbar-brand"  href="/timeline">
			<img class="img-logo-white" src="/img/x_logo_white.png" class="menuIco" />
			</a>
		</div>	
		<div class="col-auto ml-auto" >
			<a class="menuItem m-5" href="/timeline">
				Home
			</a>
			<a class="menuItem m-5" href="/sair">
				Sair
			</a>
		</div>
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<img class="perfilFoto" src="/img/<?= $this->view->info_usuario['imagem'] ?>">
						</div>
					</div>
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilTitulo">
								<?= $this->view->info_usuario['nome'] ?>
								<p class="arroba"> <?= $this->view->info_usuario['nickname'] ?> </p>
							</span>
						</div>
					</div>
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
								<p class="descricao"> <?= $this->view->info_usuario['descricao'] ?> </p>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_tweets['total_tweet']  ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="quemSeguir" method="get">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-button" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>


			<?php foreach($this->view->usuarios as $indice_arr => $usuario) { ?>
			<div class="row mb-2 text-white">
				<div class="col">
					<div class="card-segue">
						<div class="card-body">
							<div class="row">

								<div class="col-md-9">
								<img class="perfilFoto" src="/img/<?= $usuario['imagem'] ?>" alt="">
									<p class="quemSeguirTitulo"> <?= $usuario['nome'] ?> </p>
									<p class="arroba"> <?= $usuario['nickname'] ?> </p>
									<p class="arroba"> <?= $usuario['descricao'] ?> </p>
								</div>  
								<div class="col-md-3 d-flex justify-content-end">
									<div>
									<?php if($usuario['seguindo_sn'] != 1) { ?>
										<a href="/acao?acao=seguir&id_usuario=<?= $usuario['id'] ?>" class="btn btn-button">Seguir</a>
									<?php }?>
									<?php if($usuario['seguindo_sn'] != 0) { ?>
										<a  href="/acao?acao=deixar_de_seguir&id_usuario=<?= $usuario['id'] ?> " class="btn btn-button">Deixar de seguir</a>
										<?php }?>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php } ?>

		</div>
	</div>
</div>
</body>
</html>