<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Timeline</title>
</head>
<body class="bannert">
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div  class="navbar" >
		<div>
			<a class="navbar-brand"  href="/timeline">
			<img class="img-logo-white" src="/img/x_logo_white.png" class="menuIco" />
			</a>
		</div>	
		<div class="col-auto ml-auto" >
			<a class="menuItem m-5" href="/timeline">
				Home
			</a>
			<a class="menuItem m-5" href="/sair">
				Sair
			</a>
		</div>
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">
				</div>
				<div class="perfilPainel">
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<img class="perfilFoto" src="/img/<?= $this->view->info_usuario['imagem'] ?>">
						</div>
					</div>
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilTitulo">
								<?= $this->view->info_usuario['nome'] ?> <button class="btn btn-button-editar" data-toggle="modal" data-target="#editarModal"> Editar Perfil </button>
								<p class="arroba"> <?= $this->view->info_usuario['nickname'] ?> </p>
							</span>
						</div>
					</div>
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
								<p class="descricao"> <?= $this->view->info_usuario['descricao'] ?> </p>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_tweets['total_tweet']  ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-button ">Tweet</button>
						</div>
						<?php if(isset($_GET['erro']) && $_GET['erro'] == 'Erro') { ?>
							<p class="text-danger "> Erro ao inserir o tweet. Ele está em branco </p>
						<?php } ?>
					</form>
				</div>
			</div>
			
			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?> 
			<div class="row tweet">
				<div class="col">
					<img class="perfilFotoTweet" src="/img/<?= $tweet['imagem'] ?>">
					<p><strong> <?=  $tweet['nome'] ?> </strong> <span class="text text-muted">- <?= $tweet['data'] ?>  </span></p>
					<p class="arroba"> <?= $tweet['nickname'] ?> </p>
					<p> <?= $tweet['tweet']  ?>    </p>
					<br />
					<form method="get" action="/deletar">
						<div class="col d-flex justify-content-end">
							<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?> 
							<button type="submit" class="btn btn-button"><small>Remover</small></button>
							<input type="hidden" name="id" value="<?= $tweet['id'] ?>"  >
							<?php } ?>
						</div>
					</form>
				</div>
			</div>
			<?php } ?>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Edite seu perfil</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  <form action="/atualizar" method="post">
              <div class="form-group">
			  <label for="name"> Atualizar nome </label>
                <input type="text" value="<?= $this->view->info_usuario['nome']?>" name="nome"  class="form-control" placeholder="Nome">
              </div>

              <div class="form-group">
				<label for="nickname"> Atualizar nickname </label>
                <input type="text" name="nickname" value="<?= $this->view->info_usuario['nickname']?>"  class="form-control" placeholder="Preencha seu @">
              </div>
              
              <div class="form-group">
			  <label for="email"> Atualizar e-mail </label>
                <input type="text" value="<?= $this->view->info_usuario['email']?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
			  <label for="descricao"> Atualizar descricao </label>
                <input type="text" value="<?= $this->view->info_usuario['descricao']?>" name="descricao" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
			  <label for="imagem"> Atualize a foto de perfil </label>
                <input type="file" name="imagem" value="<?= $this->view->info_usuario['imagem']?>" class="form-control" placeholder="Senha"> 
              </div>
              <button type="submit" class="btn btn-button btn-block">Atualizar</button>

              <?php 
                    if($this->view->erroCadastro) {?>
                      <small class="text-danger form-text text-center"> Ocorreu um ero, por favor digite um e-mail, nome ou NickName válido </small>
                	 <?php } ?>
            </form>
      </div>
    </div>
  </div>
</div>



</body>
</html>
