<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Timeline</title>
</head>
<body class="bannert">
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div  class="navbar" >
		<div>
			<a class="navbar-brand"  href="/timeline">
			<img class="img-logo-white" src="/img/x_logo_white.png" class="menuIco" />
			</a>
		</div>	
		<div class="col-auto ml-auto" >
			<a class="menuItem m-5" href="/timeline">
				Home
			</a>
			<a class="menuItem m-5" href="/sair">
				Sair
			</a>
		</div>
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
				<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<img class="perfilFoto" src="/img/<?= $this->view->info_usuario['imagem'] ?>">
						</div>
					</div>
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilTitulo">
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_tweets['total_tweet']  ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-button ">Tweet</button>
						</div>
						<?php if(isset($_GET['erro']) && $_GET['erro'] == 'Erro') { ?>
							<p class="text-danger "> Erro ao inserir o tweet. Ele está em branco </p>
						<?php } ?>
					</form>
				</div>
			</div>
			
			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?> 
			<div class="row tweet">
				<div class="col">
					<img class="perfilFotoTweet" src="/img/<?= $this->view->info_usuario['imagem'] ?>">
					<p><strong> <?=  $tweet['nome'] ?> </strong> <span class="text text-muted">- <?= $tweet['data'] ?>  </span></p>
					<p> <?= $tweet['tweet']  ?>    </p>
					<br />
					<form method="get" action="/deletar">
						<div class="col d-flex justify-content-end">
							<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?> 
							<button type="submit" class="btn btn-button"><small>Remover</small></button>
							<input type="hidden" name="id" value="<?= $tweet['id'] ?>"  >
							<?php } ?>
						</div>
					</form>
				</div>
			</div>
			<?php } ?>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>

</body>
</html>
